[phases.setup]
packages = ["python3", "python3-pip"]

[phases.install]
commands = ["pip3 install -r requirements.txt"]

[phases.build]
commands = []

[phases.start]
commands = ["streamlit run final.py --server.port=$PORT --server.enableCORS=false"]
